apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: users-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32408
  selector:
    component: users-app
  type: NodePort
status:
  loadBalancer: {}
